### ISSUE TITLE
Mail vs Email

### ISSUE THREAD

**Issue by Spiritdude** [humhub/humhub-modules-mail#56]
Mail vs Messages vs Email (edited): I installed the module with the idea this is an intra mail/message module for humhub, but it sends email notification outside of humhub. But I like to keep the message strictly private and not sent via email anywhere but remain within the message facility of humhub, how I can do it? I did not find a way to disable it.

**Comment by programguy** [comment]
This is currently only possible through modifying the source code of the module. You need to modify the functions that cause an email to be sent when a new message is sent.

Delete the contents of "public function notify($user)" in /protected/modules/mail/models/Message.php
(See https://github.com/humhub/humhub-modules-mail/blob/master/models/Message.php#L185)

So the function can look like this:
    public function notify($user) {}
Instead of:
    public function notify($user)
    {
    <a bunch of lines of code...>
    }

Do the same thing with "public function notify()" in /protected/modules/mail/models/MessageEntry.php
(See https://github.com/humhub/humhub-modules-mail/blob/master/models/MessageEntry.php#L102)

**Comment by Spiritdude** [comment]
I just commented out the Yii::app()->mail->send(..) in both files, thanks!
